name: First CI # name of action

on: # specify the event to trigger this action
 push: 
  branches: ["master"] # trigger this action when something pushed in master branch

jobs:
 test: # job name
  runs-on: ubuntu-latest # job runner

  steps:
   - name: Checkout code
     uses: actions/checkout@v4 # use this predefined steps

   - name: Run a command
     run: echo "Learning Github Action" # execute on shell
